# permissions for end users to view keyvaultsecretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyvaultsecretsync-viewer-role
rules:
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultsecretsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultsecretsyncs/status
  verbs:
  - get
