# permissions for end users to edit keyvaultsecretsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyvaultsecretsync-editor-role
rules:
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultsecretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultsecretsyncs/status
  verbs:
  - get
