
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultcertificatesyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultcertificatesyncs/finalizers
  verbs:
  - update
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultcertificatesyncs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultsecretsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultsecretsyncs/finalizers
  verbs:
  - update
- apiGroups:
  - akv.fil.it
  resources:
  - keyvaultsecretsyncs/status
  verbs:
  - get
  - patch
  - update
